language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script: 
  - |
      if [[ $TRAVIS_PYTHON_VERSION == '3.3' || $TRAVIS_PYTHON_VERSION == '3.4' || $TRAVIS_PYTHON_VERSION == '3.5' ]]; then 
          py.test --cov=./
      else 
          pytest --cov=./
      fi
after_success:
  - codecov