language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - python -m pytest --cov='./'
after_success:
  - codecov
